Question: Perform vector addition for the following vectors: v = [2, 4, 6] and u
= [1, 3, 5].




In [ ]:
import numpy as np

v = np.array([2, 4, 6])
u = np.array([1, 3, 5])
u_v = u + v
print(u_v)

[ 3  7 11]


Question: Calculate the dot product of vectors v = [2, 4, 6] and u = [1, 3, 5].



In [ ]:
v = np.array([2, 4, 6])
u = np.array([1, 3, 5])
uv = np.dot(v, u)
print(uv)

44


Question: Find the norm (magnitude) of vector v = [3, -4, 5].



In [ ]:
from numpy.linalg import norm

v = np.array([3, -4, 5])
nor = norm(v)
nor

7.0710678118654755

Question: Given matrix A = [[1, 2], [3, 4]] and matrix B = [[5, 6], [7, 8]], perform
matrix multiplication A * B.



In [ ]:
 A = np.array([[1, 2],
               [3, 4]])

 B = np.array([[5, 6],
               [7, 8]])

 mat_mul_A_B = np.matmul(A, B)
 print(mat_mul_A_B)

[[19 22]
 [43 50]]


Question: Calculate the determinant of matrix A = [[3, 1], [2, 4]].



In [ ]:
from numpy.linalg import det

A = np.array([[3, 1], [2, 4]])

det_m = det(A)
print(det_m)

10.000000000000002


Question: Find the inverse of matrix A = [[2, 1], [4, 3]].



In [ ]:
from numpy.linalg import inv

A = np.array([[2, 1], [4, 3]])
Inverse = inv(A)
print(Inverse)

[[ 1.5 -0.5]
 [-2.   1. ]]


Question: Perform gradient descent to find the minimum of the function f(x) =
x^2 + 2x - 3 starting from an initial value of x = 0 with a learning rate of 0.1.
Perform three iterations.



Question: Given a function f(x, y) = x^2 + y^2, calculate the partial derivatives
∂f/∂x and ∂f/∂y.



In [ ]:
import sympy as sy

x, y = sy.symbols('x y')

f = x**2 + y**2
d_f_x = sy.diff(f, x)
d_f_y = sy.diff(f, y)

print("df/dx :", d_f_x)
print("df/dy :", d_f_y)


df/dx : 2*x
df/dy : 2*y


Question: Apply the chain rule to find the derivative of the function f(x) = (x^2+ 1)^3.



In [ ]:
import sympy as sp


x, u = sp.symbols('x u')

f = (x**2 + 1)**3
inner_function = x**2 + 1
outer_function = u**3

df_du = sp.diff(outer_function, u)
du_dx = sp.diff(inner_function, x)

df_dx = df_du * du_dx       # As per cahin rule df/dx = (df/du) * (du/dx)

print("Derivative of f(x) =", df_dx)


Derivative of f(x) = 6*u**2*x


Question: Use gradient descent to optimize the parameters (m and b) of a
linear regression model. Given a dataset with inputs X and targets y, update
the parameters iteratively based on the gradients of the mean squared error
loss function until convergence.
.


Question: Calculate the cross product of vectors v = [1, 2, 3] and u = [4, 5, 6].



In [ ]:
 v = np.array([1, 2, 3])
 u = np.array([4, 5, 6])

 cross = np.cross(v, u)
 print('Cross Product :', cross)

Cross Product : [-3  6 -3]


array([ 3, -6,  3])

Question: Find the angle between vectors v = [1, 2, 3] and u = [4, 5, 6].



In [ ]:
from numpy.linalg import norm
import numpy as np

v = np.array([1, 2, 3])
u = np.array([4, 5, 6])

dot = np.dot(v, u)
mag_v = norm(v)
mag_u = norm(u)

cos_theta = dot / (mag_v * mag_u)
angle_radian = np.arccos(cos_theta)       #calculating angle in radians
angle_degree = np.degrees(angle_radian)           #angle to degrees

print('Angle in radian :', angle_radian)
print('Angle in degree :', angle_degree)


Angle in radian : 0.2257261285527342
Angle in degree : 12.933154491899135


Question: Given matrix A = [[2, 3], [4, 5]] and matrix B = [[1, 2], [3, 4]], perform
matrix addition A + B.



In [ ]:
A = np.array([[2, 3],
              [4, 5]])

B = np.array([[1, 2],
              [3, 4]])

A_B = A + B
print('Adding matrix A and B :\n', A_B)

Adding matrix A and B :
 [[3 5]
 [7 9]]


Question: Calculate the eigenvalues and eigenvectors of matrix A = [[2, 1], [1,2]].



In [ ]:
from numpy.linalg import eig

A = np.array([[2, 1], [1,2]])

value, vector = eig(A)

print('Eigen Values :\n', value)
print('\nEigen Vector :\n', vector)

Eigen Values :
 [3. 1.]

Eigen Vector :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


Question: Determine the LU factorization of matrix A = [[2, 4], [1, 3]].

In [ ]:
from scipy.linalg import lu

A = np.array([[2, 4], [1, 3]])

LU_Factor= lu(A)
LU_Factor

(array([[1., 0.],
        [0., 1.]]),
 array([[1. , 0. ],
        [0.5, 1. ]]),
 array([[2., 4.],
        [0., 1.]]))